services:

  jenkins:
    build:
      context: ./jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ci_network
    restart: unless-stopped

  agent1:
    image: jenkins/agent:latest
    container_name: jenkins_agent1
    networks:
      - ci_network
    restart: unless-stopped

  agent2:
    image: jenkins/agent:latest
    container_name: jenkins_agent2
    networks:
      - ci_network
    restart: unless-stopped

volumes:
  jenkins_home:

networks:
  ci_network:
    driver: bridge
